<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NR9f6w5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NR9f6w5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NR9f6w5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', false],
        ], [
            'managerRegistry' => '?',
            'repo' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
