<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V1RchCWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v1RchCW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v1RchCW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manger' => ['services', 'doctrine', 'getDoctrineService', false],
            'rec' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'manger' => '?',
            'rec' => 'App\\Repository\\CommentaireRepository',
        ]);
    }
}
