<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Thj9JB9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Thj9JB9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Thj9JB9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\RessourceRepository', 'getRessourceRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\RessourceRepository',
        ]);
    }
}
