<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mh9JnS1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mh9JnS1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mh9JnS1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'knpSnappyPdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
            'repo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', false],
        ], [
            'knpSnappyPdf' => '?',
            'repo' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
