<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gnn03uWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gnn03uW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gnn03uW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evalRepo' => ['privates', 'App\\Repository\\EvaluationRepository', 'getEvaluationRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'evalRepo' => 'App\\Repository\\EvaluationRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
