<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_28R_40sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.28R.40s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.28R.40s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', false],
            'repocat' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', false],
        ], [
            'repo' => 'App\\Repository\\CoursRepository',
            'repocat' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
