<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TEijTLDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tEijTLD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tEijTLD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manger' => ['services', 'doctrine', 'getDoctrineService', false],
            'rep' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'manger' => '?',
            'rep' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
