<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GhVljRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gh_vljR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gh_vljR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'repository' => ['privates', 'App\\Repository\\ReponseFirasRepository', 'getReponseFirasRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repository' => 'App\\Repository\\ReponseFirasRepository',
        ]);
    }
}
