<?php

namespace ContainerRIxSd5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionFirasRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\QuestionFirasRepository' shared autowired service.
     *
     * @return \App\Repository\QuestionFirasRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'QuestionFirasRepository.php';

        return $container->privates['App\\Repository\\QuestionFirasRepository'] = new \App\Repository\QuestionFirasRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
