<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UHjkLCfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UHjkLCf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UHjkLCf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Catrep' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', false],
            'Crep' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', false],
            'Erep' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'Prep' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'Urep' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'Catrep' => 'App\\Repository\\CategorieRepository',
            'Crep' => 'App\\Repository\\CoursRepository',
            'Erep' => 'App\\Repository\\EvenementRepository',
            'Prep' => 'App\\Repository\\ProductRepository',
            'Urep' => 'App\\Repository\\UserRepository',
        ]);
    }
}
