<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HwziO7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HwziO7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HwziO7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Repository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'Repository' => 'App\\Repository\\EvenementRepository',
            'flashy' => '?',
            'managerRegistry' => '?',
        ]);
    }
}
