<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IxdwdBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._IxdwdB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._IxdwdB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manger' => ['services', 'doctrine', 'getDoctrineService', false],
            'par' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'rec' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'rep' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'manger' => '?',
            'par' => 'App\\Repository\\UserRepository',
            'rec' => 'App\\Repository\\CommentaireRepository',
            'rep' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
