<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9akzhXWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9akzhXW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9akzhXW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'urepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'repo' => 'App\\Repository\\EvenementRepository',
            'urepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
