<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IA0khxwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iA0khxw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iA0khxw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\RessourceRepository', 'getRessourceRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'repo' => 'App\\Repository\\RessourceRepository',
        ]);
    }
}
