<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KJAnfPyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KJAnfPy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KJAnfPy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Repository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'Repository' => 'App\\Repository\\EvenementRepository',
            'managerRegistry' => '?',
        ]);
    }
}
