<?php

namespace Container63MOUjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\EvenementRepository' shared autowired service.
     *
     * @return \App\Repository\EvenementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'EvenementRepository.php';

        return $container->privates['App\\Repository\\EvenementRepository'] = new \App\Repository\EvenementRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
